In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import re
import nltk
import string
import random

random.seed(0)
np.random.seed(0)
tf.random.set_seed(42)
tf.random.set_seed(42)

from nltk.tokenize import word_tokenize
from nltk.tokenize.treebank import TreebankWordDetokenizer
print("Done")

Done


In [2]:
df = pd.read_csv("imdb.csv")

def preprocess(x):
	x = x.lower()
	x = x.encode("ascii","ignore").decode()
	x = re.sub("https*\S+"," ",x)
	x = re.sub("@\S+"," ",x)
	x = re.sub("#\S+"," ",x)
	x = re.sub("\'\w+","",x)
	x = re.sub("[%s]" % re.escape(string.punctuation)," ", x)
	x = re.sub("\w*\d+\w*","",x)
	x = re.sub("\s{2,}"," ",x)
	return x
	
temp = []
data_to_list = df["review"].values.tolist()
for i in range(len(data_to_list)):
	temp.append(preprocess(data_to_list[i]))
	
def tokenize(y):
	for x in y:
		yield(word_tokenize(str(x)))
		
data_words = list(tokenize(temp))

def detokenize(txt):
	return TreebankWordDetokenizer().detokenize(txt)
	
final_data = []
for i in range(len(data_words)):
	final_data.append(detokenize(data_words[i]))
print(final_data[:5])
final_data = np.array(final_data)

['one of the other reviewers has mentioned that after watching just oz episode you be hooked they are right as this is exactly what happened with me br br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the word br br it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to many aryans muslims gangstas latinos christians italians irish and more so scuffles death stares dodgy dealings and shady agreements are never far away br br i would say the main appeal of the show is due to the fact that it goes where other shows wouldn dare f

In [3]:
import pickle
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import backend as K
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split

max_words = 20000
max_len = 200

tokenizer = Tokenizer(num_words = max_words)
tokenizer.fit_on_texts(final_data)
sequences = tokenizer.texts_to_sequences(final_data)
tweets = pad_sequences(sequences,maxlen=max_len)
with open("tokenizer.pickle","wb") as handle:
	pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)
print(tweets)

labels = np.array(df["sentiment"])
l = []
for i in range(len(labels)):
	if labels[i]=="negative":
		l.append(0)
	elif labels[i]=="positive":
		l.append(1)
l = np.array(l)
labels = tf.keras.utils.to_categorical(l,2,dtype="int32")
del l

x_train,x_test,y_train,y_test = train_test_split(tweets,labels,random_state=42)
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train,test_size=0.25,random_state=42)

inputs = tf.keras.Input(shape=max_len,dtype="int32")
x = layers.Embedding(max_words,128)(inputs)
x = layers.GRU(64,return_sequences=True)(x)
x = layers.GRU(64)(x)
outputs = layers.Dense(2,activation="sigmoid")(x)
model = tf.keras.Model(inputs,outputs)
model.summary()

model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
checkpoint = ModelCheckpoint("model_gru.hdf5",monitor="val_accuracy",verbose=1,save_best_only=True,save_weights_only=False)
model.fit(x_train,y_train,batch_size=32,epochs=5,validation_data=(x_val,y_val),callbacks=[checkpoint])
best = tf.keras.models.load_model("model_gru.hdf5")
loss,acc = best.evaluate(x_test,y_test,verbose=2)
predictions = best.evaluate(x_test)
print("Test acc: {:.2f} %".format(100*acc))
print("Test loss: {:.2f} %".format(100*loss))

[[1031    8 2673 ...  125 4061  471]
 [   0    0    0 ... 1950   68  215]
 [   0    0    0 ...   64   17  342]
 ...
 [  48 3386    9 ... 3931    2 5882]
 [  17    1  910 ...   49  719   43]
 [   0    0    0 ...  774   11   15]]
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 200)]             0         
_________________________________________________________________
embedding (Embedding)        (None, 200, 128)          2560000   
_________________________________________________________________
gru (GRU)                    (None, 200, 64)           37248     
_________________________________________________________________
gru_1 (GRU)                  (None, 64)                24960     
_________________________________________________________________
dense (Dense)                (None, 2)                 130       
Total params: 2,622,338
Trainab